version: '3.9'

services:
  db:
    container_name: postgres
    image: bitnami/postgresql:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRESQL_USERNAME: 'postgres'
      POSTGRESQL_PASSWORD: 'postgres'
      POSTGRESQL_DATABASE: 'postgres'
    ports:
      - "5432:5432"
  app:
    depends_on:
      - db
    container_name: app
    build: .
    volumes:
      - ./logs:/app/logs
    environment:
      DB_SYNC: true
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 30M
volumes:
  db-data:
  app-logs:
