definitions:
  controllers.errorResponse:
    properties:
      error:
        example: error message
        type: string
    type: object
  controllers.userResponse:
    properties:
      createdTimestamp:
        example: 1600000000000
        type: integer
      email:
        example: example@email.com
        type: string
      firstName:
        example: John
        type: string
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      lastName:
        example: Doe
        type: string
      roles:
        example:
        - '["admin"'
        - ' "user"]'
        items:
          type: string
        type: array
      username:
        example: user1
        type: string
    type: object
  controllers.usernameResponse:
    properties:
      username:
        example: user1
        type: string
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
      tags:
      - Ping
  /user-info/{userID}:
    get:
      description: Get user
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.userResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Get user
      tags:
      - User
  /user-info/{userID}/username:
    get:
      description: Get user's username
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.usernameResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Get user's username
      tags:
      - User
  /user-info/search:
    get:
      description: Search users
      parameters:
      - description: Username
        in: query
        name: query
        required: true
        type: string
      - description: Include roles
        in: query
        name: includeRoles
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.userResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Search users
      tags:
      - User
swagger: "2.0"
